### PR TITLE
feat: add image with rounder corners and border

### LINKED ISSUE #9: feat: marianzburlea - create section title for connect

### PR DESCRIPTION
**Pull request by marianzburlea**
this closes #9, #10

### CODE REVIEW

**Review by Constantin-Matei — APPROVED** [review]
:)

**Review by MariaTeo — APPROVED** [review]
nice

**Review by BogdanNegura — APPROVED** [review]
👍

**Review by biggicode — APPROVED** [review]

**Comment by RadosavAntonio** [comment]
👌🏻

**Review by RadosavAntonio — COMMENTED** [review]
nice

**Review by Constantin-Matei — COMMENTED** [review]
:)

**Pull request merged**
